### ISSUE TITLE
M/E picker menus don't show additional buses on supported switchers

### ISSUE THREAD

**Issue by adamtow** [bitfocus/companion-module-tow-mixeffect#4]
Tried using the 2 M/E and the Constellation 8K. The M/E pickers only show M/E 1 and Selected M/E.

They should show the correct number of Mix Effect Buses available for the switcher:

2 M/E: 2
4 M/E: 4
Constellation 8K: 4

**Comment by estilles** [comment]
Thank @adamtow! I'll fix asap.

**Comment by TVcameras** [comment]
Hi Johnny & Adam!  Any chance this might get fixed in the next few days?  Got a show next week and would love to use this feature...  Would also love to try any versions of the forthcoming feedback feature...  Here is a shot of a little assignment panel I made using the "Selected" variables. It would be super useful to have the buttons light up a different color when they are assigned (like Adam did on the IPad MixEffectPro SuperSource screen...).  Thanks guys!    
Jim Hurwitz
![StreamDeck SupSrce Assigns](https://user-images.githubusercontent.com/84539770/145328425-8005a485-d696-43e3-b73d-ad5c4741b79b.jpg)
